### ISSUE TITLE
README has a wrong execution instruction

### ISSUE THREAD

**Issue by jelilat** [kurtosis-tech/onboarding-ethereum-testsuite#20]
The scripts file was probably renamed and wasn't captured in the README. But the current instruction is `bash scripts/build-and-run.sh all`. It should be `bash scripts/build.sh all` instead. 

<img width="574" alt="Screenshot 2022-08-03 at 07 48 04" src="https://user-images.githubusercontent.com/23613565/182542657-d62f9874-7e87-42b7-a677-9b64f3c8391b.png">

**Comment by leoporoli** [comment]
Fixes on this PR #21
